# Copyright 2013-2023 The Cobra Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    # - bodyclose

  - errcheck
  - goconst
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - nilerr
  - nilnil
  - revive
  - staticcheck
  - unconvert
  - unused
  # - asasalint
  # - asciicheck
  # - bidichk
  # - containedctx
  # - contextcheck
  # - cyclop
  # - deadcode
  # - decorder
  # - depguard
  # - dogsled
  # - dupl
  # - dupword
  # - durationcheck
  # - errchkjson
  # - errname
  # - errorlint
  # - execinquery
  # - exhaustive
  # - exhaustivestruct
  # - exhaustruct
  # - exportloopref
  # - forbidigo
  # - forcetypeassert
  # - funlen
  # - gci
  # - ginkgolinter
  # - gocheckcompilerdirectives
  # - gochecknoglobals
  # - gochecknoinits
  # - gocognit
  # - gocritic
  # - gocyclo
  # - godot
  # - godox
  # - goerr113
  # - gofmt
  # - gofumpt
  # - goheader
  # - gomnd
  # - gomoddirectives
  # - gomodguard
  # - goprintffuncname
  # - gosmopolitan
  # - grouper
  # - ifshort
  # - importas
  # - interfacebloat
  # - interfacer
  # - ireturn
  # - lll
  # - loggercheck
  # - maintidx
  # - makezero
  # - maligned
  # - mirror
  # - misspell
  # - musttag
  # - nakedret
  # - nestif
  # - nlreturn
  # - noctx
  # - nolintlint
  # - nonamedreturns
  # - nosnakecase
  # - nosprintfhostport
  # - paralleltest
  # - prealloc
  # - predeclared
  # - promlinter
  # - reassign
  # - rowserrcheck
  # - scopelint
  # - sqlclosecheck
  # - structcheck
  # - stylecheck
  # - tagalign
  # - tagliatelle
  # - tenv
  # - testableexamples
  # - testpackage
  # - thelper
  # - tparallel
  # - unparam
  # - usestdlibvars
  # - varcheck
  # - varnamelen
  # - wastedassign
  # - whitespace
  # - wrapcheck
  # - wsl
  # - zerologlint
  fast: false